## Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [11]:
import math

C = 50
H = 30

#define a functionm that takes input values and returns the output of the equation
def calculate_Q(D):
    Q = math.sqrt((2 * C * D) / H)
    return int(Q)

#get the input from the user as sequence
input_sequence = input("Enter comma-separated values of D: ")
print("input sequence is : ",input_sequence)

#split the input to get seperate integers
D_values = [int(x) for x in input_sequence.split(',')]

#creates a list of each output
results = [calculate_Q(D) for D in D_values]

# join thw sequence by commas again to make ot comma seperated values
output = ",".join(map(str, results))
print("output sequence is : ",output)

input sequence is :  100,150,180
output sequence is :  18,22,24



## Question 2:

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡­Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]



In [20]:
import numpy
x=3
y=5

# cerates a 2d array using numpy
matrix = numpy.array([[i*j for j in range(y)] for i in range(x)])

# prints the array shape and array
print(matrix.shape)
print(" the array is \n",matrix)

(3, 5)
 the array is 
 [[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


## Question 3:

Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

In [31]:
csv = input("ENTER THE WORDS SEPERATED BY COMMA")
print("the input sequence         : ",csv)
csv_list = csv.split(",")
csv_list.sort()
csv_list  = ",".join(csv_list)
print("the sorted output sequence : ",csv_list)

the input sequence         :  without,hellooo,bag,world
the sorted output sequence :  bag,hellooo,without,world


## Question 4:

Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [25]:
sentence = "hello world and practice makes perfect and hello world again"
print("sentence before sorting words and removing duplicates : ",sentence)
# split the sentence to take out all the words
words = sentence.split(" ")

# convert it into a set to remove all the duplicate elements
unique_words = set(words)

# sort the unique words alphanumerically
sorted_words = sorted(unique_words)

# join the sorted words into a sentence
sentence = ' '.join(sorted_words)

print("sentence after sorting words and removing duplicates  : ",sentence)

sentence before sorting words and removing duplicates :  hello world and practice makes perfect and hello world again
sentence after sorting words and removing duplicates  :  again and hello makes perfect practice world


## Question 5:

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3

In [32]:
sentence = str(input("Please enter the senetnce\n"))
print("\nEntered sentence is :",sentence)
NumberOfLetters = 0
NumberOfDigits = 0

for letter in sentence:
    if letter.isalpha():
        NumberOfLetters+=1
    elif letter.isdigit():
        NumberOfDigits+=1
    else:
        pass
print("Number of letters   : ",NumberOfLetters)
print("Number of Digits    : ",NumberOfDigits)


Entered sentence is : hello world! 123
Number of letters   :  10
Number of Digits    :  3


## Question 6:

A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1

In [59]:
import re
# import regex

# accept the input from user
InputSequence = str(input("Enter the comma seperated sequence of inputs\n "))
# just print out the input for user
print("\nEntered sequence of passwords are : ",InputSequence)

# split the sequence by commas to take out all the passowrds in it
InputPasswords = InputSequence.split(",")

# define a regex to match the password according to the given criterias
pattern = r"^(?=.*[@#$])(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[@#$A-Za-z\d]{6,12}$"

# define an empty list to store the matched passwords
MatchedPasswords = []

# define a fucntion to check the password is matching or not , the function will take the regex pattern and password as arguments
def CheckPassword(EachPassword,pattern):
    if re.match(pattern,EachPassword):
        MatchedPasswords.append(EachPassword)

# iterate through the list of passwords and call the function we have defined to check each passwords
for EachPassword in InputPasswords:
    CheckPassword(EachPassword,pattern)

# join the list bak by comma seperated values
FinalResult = ",".join(MatchedPasswords)

# check if the results are none or not, if not none then print out the results
if MatchedPasswords:
    print("\nMatched passwords are : ",FinalResult)
else:
    print("\nSorry , no passwords are matching")




Entered sequence of passwords are :  PJJgg@#22,sdfbw6326,34734ggg,297GFGcc,RTFfd@#2

Matched passwords are :  PJJgg@#22,RTFfd@#2
