## 1 Write a Python Program to Add Two Matrices?


> WE CAN JUST SIMPLY USE NUMPY TO DO MATRIX OPERATIONS

In [2]:
import numpy as np


matrix1 = np.array([[12,5,8], [5,9,7], [2,3,9]])
matrix2 = np.array([[12,5,8], [5,9,7.2], [3,9,8]])
if matrix1.size == matrix2.size:
    try:
        result = matrix1 + matrix2
        print("ADDITION OF ABOVE MATRICES ARE\n", result)
    except Exception as e:
        print("SOME ERROR OCCURED : ",e)
else:
    print("SORRY ! MATRICES SHOULD BE IN SAME SIZE FOR ADDITION")

ADDITION OF ABOVE MATRICES ARE
 [[24.  10.  16. ]
 [10.  18.  14.2]
 [ 5.  12.  17. ]]


## 2 Write a Python Program to Multiply Two Matrices?


In [10]:
import numpy as np

def multiply_matrices(matrix_a, matrix_b):

  # check if the dimensions are okay
  if matrix_a.shape[1] != matrix_b.shape[0]:
    raise ValueError("The number of columns in the first matrix must be equal to the number of rows in the second matrix")

  # calculate the product matrix
  ProductMtarix = np.dot(matrix_a, matrix_b)

  return ProductMtarix


matrix1 = np.array([[12,5,8], [5,9,7], [2,3,9]])
matrix2 = np.array([[12,5,8], [5,9,7], [3,9,8]])

ProductMatrix = multiply_matrices(matrix1, matrix2)

print(ProductMatrix)



[[193 177 195]
 [126 169 159]
 [ 66 118 109]]


## 3 Write a Python Program to Transpose a Matrix?


In [12]:
import numpy as np

matrix1 = np.array([[12,5,8], [5,9,7], [2,3,9]])

# matrix.T gives the transporse of the matrix
matrix1_transpose = matrix1.T

print(matrix1_transpose)


[[12  5  2]
 [ 5  9  3]
 [ 8  7  9]]


## 4 Write a Python Program to Sort Words in Alphabetic Order?


In [19]:
def SortWords(sentence):
    #splitting the words
    words = sentence.split()

    # lower casing all the words to make it case insensitive
    words = [word.lower() for word in words]

    #sort() function sorts the list of words
    words.sort()

    return ' '.join(words)

sentence = "India is such a beautiful country"
sorted_sentence = SortWords(sentence)
print("Actual sentence : ", sentence)
print("Sorted sentence : ", sorted_sentence)


Actual sentence :  India is such a beautiful country
Sorted sentence :  a beautiful country india is such


## 5 Write a Python Program to Remove Punctuation From a String?

In [29]:
import string
# this modeule allows us to do many string operations

def RemovePunctuation(input_string):

    translator = str.maketrans('', '', string.punctuation)
    return input_string.translate(translator)


text = "this string, 'contains' so many!! punctuations."
cleaned_text = RemovePunctuation(text)
print("Actual text                  : ", text)

print("After removal of punctuation : ", cleaned_text)


Actual text                  :  this string, 'contains' so many!! punctuations.
After removal of punctuation :  this string contains so many punctuations
